cyclomatic_complexity:
    warning : 20
    error : 30
    ignores_case_statements: true
    
line_length:
    warning: 200
    error: 250
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
type_body_length:
    warning: 300
    error: 350
    
disabled_rules:
    - inclusive_language
